refactor: update student overview tests
It's common to refactor after one or several TDD iterations.
For the following test, I didn't like:
  - The name 'studentNameElems', obviously a copy and paste mistake,
  - The expect(..).toBeTruthy() because I have already a test that check if the students are being shown. No needed,
  - The same as the previous with the length,
  - And the forEach with the string comparison

The last point is the most important for me, the other are just details. When a test fails I want to be able to see exactly what fails and the string comparison with the toBeTruthy does not allow it.

```
it('Should show every student enroll date', () => {
    const students = fakeStudents();
    wrapperComponent.content = students;
    wrapperFixture.detectChanges();

    const studentNameElems: HTMLElement[] = wrapperFixture.nativeElement.querySelectorAll('.tst-student-enroll-date');
    expect(studentNameElems).toBeTruthy();
    expect(studentNameElems.length).toBe(students.length);
    studentNameElems.forEach(elem => {
      expect(students.some(student => student.enrollDate.toDateString() === elem?.textContent?.trim())).toBeTruthy();
    });
  });
```

To improve the for each I've extracted the texts from the view for the properties I want to test on each unit test. Then, I loop throw the injected students and check if the expected output contains the student's property.

This is an example of of error log. Much clear.
```
Error: expect(received).toContain(expected) // indexOf

Expected value: "tst"
Received array: ["Thu Jan 01 1970", "Tue Jul 31 190987", "Thu Jan 29 171007", "Mon Apr 19 -271821", "Fri Feb 01 78408", "Mon Feb 13 117111", "Mon Apr 19 -271821", "Mon Aug 16 -200306", "Sat Sep 13 275760", "Thu Jan 01 1970"]
```

Footer notes:
  - I've also discovered an issue with the tests.
    - I wanted to start using [ElmLang's writing style](https://elm-lang.org/docs/style-guide) to improve git diffs
    - So, I decided to add a line break in the html tags to separate the tag from it's content
      - from this `<span>{{ student.name  }}</span>` to `<span>\n{{ student.name  }}\n</span>`
    - This produced an error in the tests because the fast-check generates text with spaces or \n characters
    - For the moment I'll keep the html single lines and fix this issue in the future with the amazing io-ts library.